# Generated by Django 4.2.2 on 2023-08-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mural', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mural',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
