# Generated by Django 4.2.2 on 2023-08-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mural', '0002_mural_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mural',
            name='email',
        ),
        migrations.RemoveField(
            model_name='mural',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mural',
            name='password',
        ),
        migrations.RemoveField(
            model_name='mural',
            name='urgencia',
        ),
        migrations.AddField(
            model_name='mural',
            name='oferece_ajuda',
            field=models.BooleanField(default=False),
        ),
    ]
