# Generated by Django 4.2.2 on 2023-08-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mural', '0003_remove_mural_email_remove_mural_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mural',
            name='contact',
            field=models.CharField(max_length=165),
        ),
    ]
